### ISSUE TITLE
Old PHP support?

### ISSUE THREAD

**Issue by LehaMotovilov** [anrw/classy#11]
А нам действительно нужна поддержка PHP 5.4 ?
Просто судя по [PHP Supported Versions](http://php.net/supported-versions.php)
Уже поддержка PHP 5.5 закончилась три дня назад...

**Comment by anrw** [comment]
Меня в этом вопросе пугает только то, что множество хостингов, которые используют клиенты в лучшем случае имеют версию PHP 5.3. Я не против шагнуть в сторону PHP 5.6+, так как имею полный контроль над своими проектами, но думаю пользовательский охват будет ниже. Ты как считаешь?

**Comment by LehaMotovilov** [comment]
1. Ну врядли мы будем сабмитить тему на wordpress.org/themes.
2. Тема больше расчитана на программистов которые понимают что происходит и я думаю они смогут поставить PHP посвежее на сервере.
3. Судя по рекомендаци https://wordpress.org/about/requirements/ Они рекомендуют PHP version 5.6, но поддерживают PHP 5.2.4+ но это вообще древний век.
   
   PS. Я уже перевел продакшен сервера на PHP 7. Так что будь бы моя воля, поставил минимально 7.0 😃

**Comment by anrw** [comment]
Признаюсь, убедил 😃

**Comment by LehaMotovilov** [comment]
Done. Сделал минимальную `"php": ">=5.6.0"`
