### ISSUE TITLE
Namespaces Classy

### ISSUE THREAD

**Issue by LehaMotovilov** [anrw/classy#12]
Есть смысл добавить `namespace Classy;`
Тогда можно будет убрать методы:

``` php
$this->define_constants();
$this->include_core_files();
$this->include_models();
```

Ну и шаг вперед к best practices. Что думаете?

**Comment by LehaMotovilov** [comment]
Сделал в отдельной ветке поддержку namespace, вот как это примерное будет выглядеть.
https://github.com/anrw/classy/tree/improvements/Namespaces/app

**Comment by anrw** [comment]
Это прекрасно! По сути это также решает проблему с константами. Т.е. префикс Classy теперь лишний, так как они в любом случае будут определены внутри namespace.

**Comment by LehaMotovilov** [comment]
Ок, супер. Ну константы пока что пусть будут. Чуть позже еще раз на них посмотрю.
Можно мержить в develop?

**Comment by anrw** [comment]
Ага :)

**Comment by LehaMotovilov** [comment]
Done.
