### ISSUE TITLE
index.php Parse error: syntax error, unexpected '::'

### ISSUE THREAD

**Issue by prBigBrother** [anrw/classy#17]
<img width="1261" alt="screen shot 2016-07-19 at 17 09 18" src="https://cloud.githubusercontent.com/assets/3617478/16952896/cf2137c4-4dd3-11e6-93c0-94a8830fdb35.png">

PHP Version 5.6.23

**Comment by LehaMotovilov** [comment]
Thanks for this issue. 
It's my bug. I'll fix it asap.

**Comment by LehaMotovilov** [comment]
Fixed and merged to master branch.
