### ISSUE TITLE
Classy/Menu class doesn't support menu locations.

### ISSUE THREAD

**Issue by konstantp** [anrw/classy#19]
`classy/app/classes/appearance.php`  registers theme locations:

```
register_nav_menus(array(
'header-menu' => __( 'Header Menu', Classy::textdomain() ),
'footer-menu' => __( 'Footer Menu', Classy::textdomain() ),
));
```

However `classy/app/classes/menu.php` doesn't support **wp_nav_menu**  function
and theme locations and to add a menu into scope you have to pass its ID.

**Comment by anrw** [comment]
Thanks @konstantp , I will make an update soon

**Comment by anrw** [comment]
Implemented and merged to master branch
