### ISSUE TITLE
Implement HTML minification as an option

### ISSUE THREAD

**Issue by anrw** [anrw/classy#20]

**Comment by LehaMotovilov** [comment]
Я не уверен что HTML minification относится к обязаностям темы. Мне кажется что это больше относится к функционалу а соответственно выносится в плагины. 
Если не ошибаюсь W3 Total Cache умеет это делать.

**Comment by anrw** [comment]
Соглашусь, но внутри темы мы все же компилируем blade в html. Отдавать минифицированный html или нет - на мой взгляд, здесь вполне логичная опция.

**Comment by LehaMotovilov** [comment]
В принципе согласен.
А как настраивать on/off minification? Через константу в коде - хорошо, но нужно наверное опцию в админку вынести.

**Comment by anrw** [comment]
Думал насчет опции в конфиге

**Comment by LehaMotovilov** [comment]
Или как вариант можно сделать почти классискую Theme Options страницу в админке.
Но я все таки тоже склоняюсь к конфигу.

**Comment by anrw** [comment]
#24
