### ISSUE TITLE
App structure refactoring

### ISSUE THREAD

**Issue by anrw** [anrw/classy#29]
Появилась идея сделать небольшой рефакторинг. Идея частично обсуждалась с @konstantp.

В текущей реализации папка `models` находится внутри `app/classes`, что на мой взгляд не очень удобно. Я предлагаю перенести модели сразу в `app`. При этом, в папке `classes` реализовать дефолтную модель **WordPress Post Type**, которую будут расширять все модели из `app/models`. Саму же папку `classes` переименовать в `core`. На выходе мы получаем изолированный `core` от кастомной функциональности, что дает также возможность его обновлять внутри проекта.

Что думаешь @LehaMotovilov ?

**Comment by LehaMotovilov** [comment]
Насколько я понял, вы предлагаете вот такую структуру?
<img width="316" alt="screenshot 2016-08-10 09 58 43" src="https://cloud.githubusercontent.com/assets/6247404/17544611/0e90ac82-5ee1-11e6-9d28-a8d94ea9f93a.png">

**Comment by anrw** [comment]
Не совсем. Глянь на branch `app-refactoring`:
https://github.com/anrw/classy/tree/app-refactoring/app

**Comment by LehaMotovilov** [comment]
Угу, понял. А где писать кастомный код? Может стоит сделать какую-то директорию `custom`?

**Comment by anrw** [comment]
Я предполагал, что кастомный код будет в `functions` и `models`. По сути большая часть функциональности моделей будет реализована в `core`. В папке же `models` будут классы которые соответственно расширяют своих родителей, предоставляя возможность их кастомизирозовать (по дефолту они будут пустые).

Мы можем конечно все заврапить в папку `custom`, но не будет ли это излишним?

**Comment by anrw** [comment]
А что если мы определим функцию `get_theme_framework` непосредственно в `functions.php`? Таким образом избавившись полностью от папки `functions`. 

В этом случае можем смело создавать папку `custom` рядом с `models`. 🙂

**Comment by LehaMotovilov** [comment]
> Я предполагал, что кастомный код будет в functions и models.

Мне кажется кастомный код может быть больше чем кастомные functions/models. Например какой-нить модуль related items. Там и логика в классах и свои открытые для шаблона функции. И для таких модулей как раз будет директория custom. 

> А что если мы определим функцию `get_theme_framework` непосредственно в `functions.php`

Не хотелось бы захламлять `functions.php` так как у нас могут еще появиться функции (по типу врапперов) например метод `render` (аналог `get_template_part`) или еще какие-то. Эти открытые функции будут как бы частью core.

Да и теже `models` например у нас есть CPT Reviews у которых кроме регистрации и враппера над WP_Post есть какой-то логический функционал например связи post 2 post с CPT Products. По хорошему мы можем предложить программистам писать такой код в директории `custom`. 

Так что мне кажется вариант с `app/core` и `app/custom` достаточно гибкий. 
Мне кажется я не совсем понял идеологию models. Это базовый класы для расширения? Или ты планировал писать там кастомный функционал характерный для каждого сайта?

**Comment by anrw** [comment]
> Мне кажется кастомный код может быть больше чем кастомные functions/models. Например какой-нить модуль related items. Там и логика в классах и свои открытые для шаблона функции. И для таких модулей как раз будет директория custom.

Согласен. Здесь добавляется только вопрос о том, как мы будем регистрировать подобные модули? В конфиге?

> Не хотелось бы захламлять functions.php так как у нас могут еще появиться функции (по типу врапперов) например метод render (аналог get_template_part) или еще какие-то. Эти открытые функции будут как бы частью core.

Согласен

> Да и теже models например у нас есть CPT Reviews у которых кроме регистрации и враппера над WP_Post есть какой-то логический функционал например связи post 2 post с CPT Products. По хорошему мы можем предложить программистам писать такой код в директории custom.

Я думаю, что будет правильнее если данная логика будет описана в моделях.  Подобный подход используется в `Laravel Eloquent`.

> Мне кажется я не совсем понял идеологию models. Это базовый класы для расширения? Или ты планировал писать там кастомный функционал характерный для каждого сайта?

Суть в том, что у нас будут базовые классы для работы с Users, Post Types и Image. Эти классы будут описаны в `core` и предоставлять базовый функционал. Предполагается, что их не будут вызывать прямо, а использовать дочерние классы, которые будут зарегистрированы в `models`, где пользователь и сможет описать relationships с другими моделями,  кастомные методы и т.п. Ну или создать отдельный класс для работы с зарегистрированным им пост тайпом.

**Comment by LehaMotovilov** [comment]
> Согласен. Здесь добавляется только вопрос о том, как мы будем регистрировать подобные модули? В конфиге?

У меня в проектах да, через конфиг. Например: `some-config.php`

``` php
/**
 * Return modules config.
 */
return [
    'rest-api' => [
        'autoload' => true,
        'class' => '\Acme\Modules\Rest_API\Rest_API',
        'params' => [
            'some_param' => 1,
            'some_another_param' => 2,
        ],
    ],
    'redirects' => [
        'autoload' => false,
        'class' => '\Acme\Modules\Redirects\Redirects',
    ],
];
```

На счет `functions.php` - хорошо что пришли к одному мнению 😊 👍 

> Я думаю, что будет правильнее если данная логика будет описана в моделях. Подобный подход используется в Laravel Eloquent.

Я понимаю, просто не хочется что бы директория `models` была с over100500 файлов, а то в большом проекте получится как с директорией `wp-includes` 😀

> Суть в том, что у нас будут базовые классы для работы с Users, Post Types и Image. Эти классы будут описаны в core и предоставлять базовый функционал. Предполагается, что их не будут вызывать прямо, а использовать дочерние классы, которые будут зарегистрированы в `models`, где пользователь и сможет описать relationships с другими моделями, кастомные методы и т.п. Ну или создать отдельный класс для работы с зарегистрированным им пост тайпом.

Итого получается что `models` будет лежать в директории с `custom`? 

@konstantp что думаешь? 😊

**Comment by konstantp** [comment]
Всем привет!

Я для своего текущего проекта уже переделал структуру. В идеале я вижу это так:

```
/app
    /core (core can't be changed by developer and can be update only with release of the new Classy version)
        /models (default extendable models)
        /classes (core classy classes)
    /custom
        /functions (files with your custom functions, or even modules written as classes)
        /models (your custom models or extended default models )
        /widgets (custom widgets)
/scope
/views
```

**Comment by konstantp** [comment]
Получается `models` есть и в `core` и в `custom`.

**Comment by LehaMotovilov** [comment]
Так что, какой финальный вариант выбираем?

**Comment by anrw** [comment]
Проще говоря - все сложно 😀

Мне понравилась твоя идея с модулями, но на большинстве проектов, во всяком случае у нас с @konstantp - она излишне. Но было бы хорошо из коробки предоставить и тот и другой вариант.  Я вижу это как:

```
/app
    /core (core can't be changed by developer and can be update only with release of the new Classy version)
        /models (default extendable models)
        /classes (core classy classes)
    /custom
        /models (примитивные модели, которые не включаются не в один модуль и представляют собой просто класс для работы с  пост тайпом)
        /modules (модели объединенные по логическому критерию с большим количеством логики, кастомными реврайтам, апиренсом и т.п.)
        config.php - собственно место, где будут регистрироваться модули и папки которые необходимо дополнительно заинитить, например "widgets", "functions"
/scope
/views
```

**Comment by LehaMotovilov** [comment]
Хорошо, понял тебя. 😊
Но может добавим все таки директорию `functions` в `core`?
Пусть там лежат открытые функции для прямых вызовов в шаблоне? Например какой-нить `get_featured_image_src( $post_id );`. Ведь все таки `get_featured_image_src` проще вызвать в шаблоне функцию чем метод класса `Classy\Models\SomeCoolModel\Image::get_image( $entity_id );`. Тем более вдруг мы при следующем рефакторинге решим переименовать класс `Image` в `ImageHelper` - в таком случае нужно будет делать search & replace по всем шаблонам что не сильно удобно.

В общем мне кажется как-то вот так:

```
/app
    /core
        /models
        /classes
        /functions
    /custom
        /xxx - Любая директория на откуп разработчиков тем. 
        config.php 
/scope
/views
```

А на счет модулей, тут я думаю тема для отдельного разговора 😊

**Comment by LehaMotovilov** [comment]
Кстати, вот первая идея для `functions`
Вот этот код

``` php
$framework = get_theme_framework();
$framework::render( 'layout.header' );
```

можно переместить в функцию `classy_render( $layout );` и разместить ее например в `app/core/functions/render.php`

**Comment by anrw** [comment]
Насчет `functions` я согласен, просто пропустил ее в своем мокапе 😇

Последний вариант самый лучший. Что скажешь @konstantp?

**Comment by konstantp** [comment]
Да, мне все нравится, все логично структурировано.

**Comment by LehaMotovilov** [comment]
Супер, тогда @anrw ждем реквеста 😊

**Comment by LehaMotovilov** [comment]
Я так понимаю этот issue можно закрывать, так как https://github.com/anrw/classy/pull/31 уже в master.
