### ISSUE TITLE
@php, @continue(), $loop

### ISSUE THREAD

**Issue by buynitskysergey** [anrw/classy#37]
Очень не хватает возможностей @php, @continue(), $loop... Полагаю, связано с тем, что поддержка разработки Classy закончилась до появления этих директив в Blade))) Можно ли лелеять надежду на обновление?) Или если совсем нет времени, укажите в каком направлении двигаться, чтобы обновить его самостоятельно.

**Comment by anrw** [comment]
Обновил зависимости, теперь все должно работать 🙂

**Comment by buynitskysergey** [comment]
Не ожидал, что будет достаточно обновить только зависимости пакетов - слишком уж существенные различия (сравнивал с последним ларавелем). (: Спасибо за оперативный отклик, и всю работу в целом. Классная штука получилась!)
