### ISSUE TITLE
Question: Dynamic define constants.

### ISSUE THREAD

**Issue by LehaMotovilov** [anrw/classy#6]
При динамическом определении констант в методе Classy->define_constants(), моя IDE PhpStorm не понимает что вообще происходит и при каждом обращении к именовоной константе, например к THEME_PATH выдает warning "Undefined constant" и соответственно не работает goto definition. 

Может быть есть смысл оставить более прямой вариант без враппера Classy->define()? 
Что думаешь по этому поводу?

**Comment by chief93** [comment]
Поддерживаю, вообще лучше всегда объявлять константы через `const`. `define` нужно в очень специфических случаях и на самом деле это тревожный звоночек, если приходится динамически объявлять константы.

Если нужно таким образом организовать некоторое подобие свойств, то лучше это делать как методы, например (учитывая контекст, очевидно это должно быть статическое свойство):

``` php
public static function ThemePath ($path = '') {
    if (func_num_args() != 0)
        self::$_themePath = $path;

    return self::$_themePath;
}
```

или соответственно можно сделать свойство экземпляра:

``` php
public function ThemePath ($path = '') {
    if (func_num_args() != 0)
        $this->_themePath = $path;

    return $this->_themePath;
}
```

P.S. Ещё желательно это дополнить PHPDoc'ом:

``` php
/**
 * @param string $path = ''
 * 
 * @return string
 */
public function ThemePath ($path = '') {
    if (func_num_args() != 0)
        $this->_themePath = $path;

    return $this->_themePath;
}
```

**Comment by anrw** [comment]
Враппер `Classy->define` позволяет защититься от случаев когда константа уже определена чем нибудь другим. В нашем случае это очень актуально так как используются довольно дефолтные именования: _THEME_, _THEME_NAME_, _THEME_PATH_ и т.д

Я вижу два варианта решения проблемы:
1) добавить префикс каждой константе: _THEME -> CLASSY_THEME_ и регистрировать константы без врапперов.
2) Пойти по пути предложенному @chief93 и вынести константы в статические методы внутри основного класса.

Для меня привлекательнее первый вариант, так как с константами, на мой взгляд, легче работать и код выглядит чище.

**Comment by anrw** [comment]
#10

**Comment by anrw** [comment]
#10
